name: Cypress Test

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install ssi
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: npm i


      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          start: npm run start:ssi
          wait-on: 'http://localhost:3000'