name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: pnpm
          - name: Install PNPM
            run: npm i -g pnpm
      - name: Install & Build
        run: pnpm i  &&  pnpm build     
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: git submodule update --init --recursive && npm install 
          start: npm run start:ssi